# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc79dac048eeec72c8e4381432a2f79eb7af0fd6272c987e279aea9ae637d53fdcc62aad240355dbe2632f5fd21225f8a051a5618e99884af68dc7704bf4009

test:
  secret_key_base: 997c9f33f4af9516445991656e0b9016cbb52283cadb92c51f0fe47ef7c33a3d4e94ed19e4be93832f98b49b4f01f89ac203ee26f118bf33380ebcd08689c7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
